sftp:
  container_name: sftp
  image: genee/sftp
  restart: always
  privileged: true
  ports:
  - "4322:22"
  environment:
  - "FTP_USER=sftp"
  - "FTP_PASS=sftp"
  volumes:
  - "<YOUR_FTP_DIRECTORY>:/var/lib/jail/ftp"
