ftp:
  container_name: ftp
  image: genee/ftp
  restart: always
  ports:
  - 20-21:20-21
  - 43000-43100:43000-43100
  environment:
  #默认用户名密码为genee:83719730
  #- "FTP_USER=<YOUR_CUSTOM_FTP_USER>|gftp"
  #- "FTP_PASS=<YOUR_CUSTOM_FTP_PASSWD>|gftp"
  #此处PASV_ADDRESS应设置为服务器外网ip，用于被动模式,必须填写
  - "PASV_ADDRESS=<YOUR_EXTERNAL_IP>"
  volumes:
  - <YOUR_FTP_DIRECTORY>:/data
