FROM alpine:3.7
LABEL maintainer="iamfat@gmail.com" 

RUN apk add --no-cache mariadb mariadb-client bash \
    && mkdir /app \
    && echo 'export PATH="/app/bin:$PATH"' > /etc/profile.d/docker

ADD bin /app/bin

WORKDIR /app

EXPOSE 3306

ENV PATH=/app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

CMD ["/app/bin/run"]
